AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Set up lab

Parameters:
    # setup lambda script
    ScriptBucketName: 
      Type: String
      Description: Enter the bucket name for lambda script.
      AllowedPattern: ^[a-z0-9.-]+$
    FaceRecognitionLambdaScript:
      Type: String
      Description: Enter the script for FaceRecognition lambda.
      Default: lambda_script/FaceRecognition.zip
    ReadDBLambdaScript:
      Type: String
      Description: Enter the script for Read DB lambda.
      Default: lambda_script/ReadDB.zip
    # create S3 bucket
    FaceBucketName: 
      Type: String
      Description: Create a bucket with a unique name.
      AllowedPattern: ^[a-z0-9.-]+$
      ConstraintDescription: Malformed input-Parameter S3DataRepositoryBucketName must be unique and only contain lowercase letters and numbers
    # create lambda function
    FaceRecognitionLambdaName:
      Type: String
      Description: Enter your lambda name here.
      Default: "Lab-FaceRecognition"
    RegionName:
      Type: String
      Description: Enter your region name here.
      Default: "us-east-1"
    ReadDBLambdaName:
      Type: String
      Description: Enter your lambda name here.
      Default: "Lab-ReadDB"
    # create dynamodb
    FaceIndexTableName:
      Description: 'Enter the name for face index table.'
      Type: String
      Default: lab_face_index
    FaceRecordTableName:
      Description: 'Enter the name for face record table.'
      Type: String
      Default: lab_face_record
    # create IAM role
    FaceRecognitionRoleName:
      Description: 'Enter the role name for lambda.'
      Type: String
      Default: Lab-FaceRecognition-role
    # create iot rule
    IoTRuleName:
      Description: 'Enter the name for IoT rule.'
      Type: String
      Default: LabSendLambda
    SQLcommand:
      Description: 'Enter SQL command for IoT rule. IoT rule will subscribe the following topic name.'
      Type: String
      Default: Select * from 'face/image'
    # create rekognition collection 
    RekognitionCollectionName:
      Description: 'Enter the name for rekognition collection.'
      Type: String
      Default: Lab-face-collection
    # create api gateway
    ApiGatewayName:
      Description: 'Enter the name for api gateway.'
      Type: String
      Default: Lab-API

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - Label: 
          default: "S3 Bucket Configuration"
        Parameters: 
          - ScriptBucketName
          - FaceBucketName
      - Label: 
          default: "IAM Role Configuration"
        Parameters: 
          - FaceRecognitionRoleName
      - Label: 
          default: "Lambda Configuration - Face Recognition"
        Parameters: 
          - FaceRecognitionLambdaName
          - FaceRecognitionLambdaScript
          - RegionName
      - Label: 
          default: "Lambda Configuration - ReadDB"
        Parameters: 
          - ReadDBLambdaName
          - ReadDBLambdaScript
      - Label:
          default: "DynamoDB Configuration"
        Parameters: 
          - FaceIndexTableName
          - FaceRecordTableName
      - Label:
          default: "IoT Configuration"
        Parameters: 
          - IoTRuleName
      - Label:
          default: "Rekognition Configuration"
        Parameters: 
          - RekognitionCollectionName
      - Label:
          default: "API Gateway Configuration"
        Parameters: 
          - ApiGatewayName
      

Resources:
    ## IAM Role
    FaceRecognitionRole: 
      Type: AWS::IAM::Role
      Properties:
        Path: "/"
        ManagedPolicyArns: 
          - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
          - 'arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess'
          - 'arn:aws:iam::aws:policy/AmazonRekognitionFullAccess'
          - 'arn:aws:iam::aws:policy/CloudWatchLogsFullAccess'
          - 'arn:aws:iam::aws:policy/AWSIoTFullAccess'
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - 
            Action: sts:AssumeRole  
            Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
        RoleName: !Ref FaceRecognitionRoleName

    ## lambda
    FaceRecognitionLambda:
      Type: AWS::Lambda::Function
      Properties:
        FunctionName: !Ref FaceRecognitionLambdaName
        Code:
          # Choose your script in a specific S3 bucket.
          S3Bucket: !Ref ScriptBucketName
          S3Key: !Ref FaceRecognitionLambdaScript
        Handler: lambda_function.lambda_handler
        Role: !GetAtt FaceRecognitionRole.Arn
        Runtime: python3.7
        Timeout: 300 
        Environment:
          Variables:
            REGION : !Ref RegionName
            BUCKET: !Ref FaceBucketName
            COLLECTION: !Ref RekognitionCollectionName
            FACE_TABLE: !Ref FaceIndexTableName
            STREAM_RECORD: !Ref FaceRecordTableName

    ReadDBLambda:
      Type: AWS::Lambda::Function
      Properties:
        FunctionName: !Ref ReadDBLambdaName
        Code:
          # Choose your script in a specific S3 bucket.
          S3Bucket: !Ref ScriptBucketName
          S3Key: !Ref ReadDBLambdaScript
        Handler: lambda_function.lambda_handler
        Role: !GetAtt FaceRecognitionRole.Arn
        Runtime: python3.7
        Timeout: 300
        Environment:
          Variables:
            TABLE: !Ref FaceRecordTableName 

    # S3 event
    FaceDataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Ref FaceBucketName
    #     NotificationConfiguration:
    #       LambdaConfigurations:
    #       - Event: 's3:ObjectCreated:Put'
    #         Function: !GetAtt FaceRecognitionLambda.Arn
    # SetPermissionBucket1:
    #   Type: AWS::Lambda::Permission
    #   Properties:
    #     Action: 'lambda:InvokeFunction'
    #     FunctionName: !Ref FaceRecognitionLambda
    #     Principal: s3.amazonaws.com
    #     SourceAccount: !Ref "AWS::AccountId"
    #     SourceArn: !Sub "arn:aws:s3:::${FaceBucketName}"

    # iot rule setup
    IotRule:
      Type: AWS::IoT::TopicRule
      Properties: 
        RuleName: !Ref IoTRuleName
        TopicRulePayload: 
          Sql:  !Ref SQLcommand  # subscribe to topic 
          RuleDisabled: false
          Actions:
            - Lambda:
               FunctionArn: !GetAtt FaceRecognitionLambda.Arn

    # DynamoDB
    FaceIndexTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: !Ref FaceIndexTableName
        AttributeDefinitions:
          - AttributeName: "face_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "face_id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    FaceRecordTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: !Ref FaceRecordTableName
        AttributeDefinitions:
          - AttributeName: "record_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "record_id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

     ## API Gateway
    ApiGateway:
      Type: "AWS::ApiGateway::RestApi"
      Properties:
        Name: !Ref ApiGatewayName
    ApiGatewayResource:
      Type: AWS::ApiGateway::Resource
      Properties: 
        ParentId: !GetAtt ApiGateway.RootResourceId
        PathPart: "lab"
        RestApiId: !Ref ApiGateway

    ApiGatewayRootMethod:
      Type: "AWS::ApiGateway::Method"
      Properties:
        AuthorizationType: "NONE"
        HttpMethod: "GET"
        Integration:
          IntegrationHttpMethod: "GET"
          Type: "AWS_PROXY"
          Uri: !Sub
            - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"
            - lambdaArn: !GetAtt ReadDBLambda.Arn
        ResourceId: !Ref ApiGatewayResource
        RestApiId: !Ref "ApiGateway"

    ApiGatewayStage:
      Type: AWS::ApiGateway::Stage
      Properties:
        StageName: "lab"
        Description: 'lab env'
        RestApiId: !Ref "ApiGateway"
        DeploymentId: !Ref ApiGatewayDeployment
    ApiGatewayDeployment:
      Type: "AWS::ApiGateway::Deployment"
      DependsOn:
        - "ApiGatewayRootMethod"
      Properties:
        RestApiId: !Ref "ApiGateway" 